name: Build and Upload Executable

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Required Packages
        run: |
          # Install required packages
          # For example, you can install PyQt, pyinstaller, and pytest
          # pip install PyQt5 pyinstaller pytest

      - name: Build Executable
        run: |
          # Replace with your build command, for example:
          # pyinstaller --onefile your_script.py
          echo "Build script here"

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: my_executables
          path: dist
- name: Commit and Push Executable
  run: |
    git config --local user.email "dsw43125@student.dsw.edu.pl"
    git config --local user.name "ElDaifuku"

    git checkout main
    git pull origin main

    mv dist/main.exe main.exe

    git add main.exe
    git commit -m "Add the latest executable"
    git push origin main

    git remote add ghorigin "https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
    git push ghorigin main
  env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}



