name: Build and Replace Executable

on:
  workflow_run:
    workflows: ["Automated Testing"]
    types:
      - completed
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Adjust as needed

      - name: Build main.exe
        run: pyinstaller --onefile main.py

      - name: Replace main.exe in main branch
        run: |
          git config --local user.email "dsw43125@student.dsw.edu.pl"
          git config --local user.name "ElDaifuku"
          
          git checkout main
          
          Remove-Item main.exe -ErrorAction SilentlyContinue
          
          # Move the newly built main.exe to the root directory
          Move-Item dist\main.exe . -Force
              
          git add main.exe
          git commit -m "Update main.exe with the latest executable"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


















