name: Build and Upload Executable

on:
  workflow_run:
    workflows: ["Automated Testing"]
    types:
      - completed
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This job does nothing"

  build:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Create dist directory
        run: New-Item -ItemType Directory -Force -Path dist

      - name: Check if main.exe exists and Rename
        run: |
          if (Test-Path main.exe) {
            mv main.exe dist/main-old.exe
          }
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: my_executables
          path: dist

      - name: Commit and Push Executable
        run: |
          git config --local user.email "dsw43125@student.dsw.edu.pl"
          git config --local user.name "ElDaifuku"
          git checkout main
          git pull origin main

          Remove-Item main.exe -ErrorAction SilentlyContinue

          git add dist/main-old.exe dist/main.exe
          git commit -m "Add the latest executable and create backup"
          git push origin main
          git remote add ghorigin "https://$GH_TOKEN@github.com/ElDaifuku/Actions.git"
          git push ghorigin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}










