name: Build and Upload Executable

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check if main.exe exists
        run: |
          if (Test-Path main.exe) {
            Rename-Item -Path main.exe -NewName main-old.exe
          }
        continue-on-error: true

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: my_executables
          path: dist

      - name: Commit and Push Executable
        run: |
          git config --local user.email "dsw43125@student.dsw.edu.pl"
          git config --local user.name "ElDaifuku"
          git checkout main
          git pull origin main

          if (Test-Path main.exe) {
            Remove-Item main.exe
          }

          mv dist/main.exe main.exe

          git add main.exe
          git commit -m "Add the latest executable"
          git push origin main
          git remote add ghorigin "https://$GH_TOKEN@github.com/ElDaifuku/Actions.git"
          git push ghorigin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}





